name: Hello Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Hello Message
        run: echo "Build started 🛠️ via GitHub Actions"
